name: CD - Deploy to stage

on:
  push:
    branches:
      - feature-stage-i

jobs:
  deploy-stage:
    uses: ops-migration/central-shared-workflow/.github/workflows/cd-workflow.yml@main
    with:
      ecs-cluster: "stage-app"
      ecs-service: "stage-app"
      cf-stack-name: "stage-ecs-stack"
      target-env: "stage"
      environment-name: "stage"
      environment-url: "https://stage-app.com"
      aws-region: "us-east-1"
