name: CD - Deploy to prod

on:
  push:
    branches:
      - feature-prod-i

jobs:
  deploy-prod:
    uses: ops-migration/central-shared-workflow/.github/workflows/cd-workflow.yml@main
    with:
      ecs-cluster: "prod-app"
      ecs-service: "prod-app"
      cf-stack-name: "prod-ecs-stack"
      target-env: "prod"
      environment-name: "prod"
      environment-url: "https://prod-app.com"
      aws-region: "us-east-1"
