name: CD - Deploy to dev

on:
  push:
    branches:
      - feature-dev-i

jobs:
  deploy-qa:
    uses: ops-migration/central-shared-workflow/.github/workflows/cd-workflow.yml@main
    with:
      ecs-cluster: "dev-app"
      ecs-service: "dev-app"
      cf-stack-name: "dev-ecs-stack"
      target-env: "dev"
      environment-name: "dev"
      environment-url: "https://dev-app.com"
      aws-region: "us-east-1"
